name: forex
description: A multi-platform API to retrieve currency exchange prices.
version: 0.1.0
author: "Ismael Jim√©nez <ijimenezm@hotmail.es>"
homepage: https://github.com/ismaelJimenez/forex

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0
  logger: ^0.7.0+2
  meta: ^1.1.7
  xml: ^3.5.0
  finance_quote: ^0.1.2

dev_dependencies:
  test: '>=1.3.0 <1.6.8'
  mockito: ^4.1.0
  pedantic: ^1.8.0+1
